spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.tomcat.threads.max=4
spring.servlet.multipart.max-file-size=32MB
spring.servlet.multipart.max-request-size=32MB

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

eisenhower.jwt.signingkey=${JWT_SIGNING_KEY}

spring.mail.host=${MAIL_SMTP_HOST}
spring.mail.port=${MAIL_SMTP_PORT}
spring.mail.username=${MAIL_SMTP_USER}
spring.mail.password=${MAIL_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
eisenhower.mail.from=${MAIL_FROM}
eisenhower.app.base-url=${APP_BASE_URL}